### ISSUE TITLE
IndexOutOfRangeException when TimeScale is 0 (game paused)

### ISSUE THREAD

**Issue by xDavidLeon** [Tayx94/graphy#1]
Hi,

Whenever the TimeScale is 0, the console spits out:

> [Exception] [Tayx/Graphy - Ultimate Stats Monitor/Scripts/Util/NumString.cs:76] [1251] (154) IndexOutOfRangeException: Index was outside the bounds of the array.

A possible solution is to change line 66 of FpsMonitor.cs to:

`m_currentFps` = 1 / unscaledDeltaTime;

Kind Regards,
- David León

**Comment by Tayx94** [comment]
Good catch @xDavidLeon ! Thanks for pointing it out. Fixed and updated :)
