### ISSUE TITLE
If the hotkeys are enabled but any of them are set to Key.None, an IndexOutOfBounds exception is thrown

### ISSUE THREAD

**Issue by Tayx94** [Tayx94/graphy#102]
From trueh in the Unity Forums:

I have detected a little bug when using Graphy with the New Input System in Unity 2021.3. If the hotkeys are enabled but any of them are set to Key.None, an IndexOutOfBounds exception is thrown. It is easy to solve in GraphyManager.
CheckForHotkeyPresses().

**Comment by ManuelRauber** [comment]
> From trueh in the Unity Forums:
> 
> I have detected a little bug when using Graphy with the New Input System in Unity 2021.3. If the hotkeys are enabled but any of them are set to Key.None, an IndexOutOfBounds exception is thrown. It is easy to solve in GraphyManager. CheckForHotkeyPresses().

Can I contribute this? :)

**Comment by Tayx94** [comment]
Of course! Thanks for your help. PR into master is fine 👍
