### ISSUE TITLE
RAM value decreases to negative values. Unity 2022.2.1f1, Apple Silicon

### ISSUE THREAD

**Issue by nulleof** [Tayx94/graphy#103]
Ram usage decreases to negative values in playmode even in empty project.

After restarting playmode ram continues decreasing from the last negative value

<img width="873" alt="image" src="https://user-images.githubusercontent.com/5653775/215190520-03c94ea9-fc58-4f4a-9e4d-d4748c647d05.png">

**Comment by Tayx94** [comment]
I'll close this because it looks like a Unity bug, not Graphy related.
