### ISSUE TITLE
G_GraphShader.UpdateArray() should be renamed

### ISSUE THREAD

**Issue by JohannesMP** [Tayx94/graphy#104]
The comment on `G_GraphShader.UpdateArray()` states:

> Updates the material linked with this shader graph with the values in the float[] array.

The name "UpdateArray" would back this up.

However the implementation of this function doesn't pass any array data. It only sets the shader's array size value:
https://github.com/Tayx94/graphy/blob/b45856455eacfc7eca8fdd291888f5d3f20e7cf2/Runtime/Shader/G_GraphShader.cs#L75-L81

Its name and comment should be changed to match its behavior.

For example `void UpdateArrayLength()` or `void UpdatePointCount()`

**Comment by Tayx94** [comment]
Good find! Feel free to fix that and open a pull request. Else I'll get to this at some point 😄

**Comment by Tayx94** [comment]
Done!
