### ISSUE TITLE
'Resolution.refreshRate' is obsolete: 'Resolution.refreshRate is obsolete. Use refreshRateRatio instead.'

### ISSUE THREAD

**Issue by Tayx94** [Tayx94/graphy#107]
Warning in Unity 2022.3.0

`Assets/Graphy - Ultimate Stats Monitor/Runtime/Advanced/G_AdvancedData.cs(306,19): warning CS0618: 'Resolution.refreshRate' is obsolete: 'Resolution.refreshRate is obsolete. Use refreshRateRatio instead.'`

**Comment by jimanjr** [comment]
This also breaks when using Device Simulator instead of the normal Game window. With the Simulator, `Resolution.currentResolution.refreshRate` returns `-2147483648` (in Unity 2022.3.3) and therefore crashes the `ToStringNonAlloc()` function.

**Comment by Tayx94** [comment]
Fixed! Let me know if it happens again.
