### ISSUE TITLE
Getting compile error after importing

### ISSUE THREAD

**Issue by EthanSK** [Tayx94/graphy#108]
'GraphyManager' does not contain a definition for 'TimeToResetMinMaxFps' and no accessible extension method 'TimeToResetMinMaxFps' accepting a first argument of type 'GraphyManager' could be found (are you missing a using directive or an assembly reference?)[CS1061](https://msdn.microsoft.com/query/roslyn.query?appId%3Droslyn%26k%3Dk%28CS1061%29)

**Comment by EthanSK** [comment]
was using the unity asset store version. is there a reason this isn't being kept up to date?

**Comment by Tayx94** [comment]
Updated the asset store version, it will be the same as github in a couple of days, just waiting for Unity to approve
