### ISSUE TITLE
how to have two graphy prefabs in the same scene

### ISSUE THREAD

**Issue by mgarbade** [Tayx94/graphy#109]
I want to have a button to toggle the Game FPS and another button to toggle the Advanced (system information).

However, there are errors when I try to do that.

Is that even possible?

Or does the graphy Manager make sure there is only one global instance per scene?

**Comment by Tayx94** [comment]
Yes, GraphyManager is a Singleton so the last one to be created will be Destroyed on creation. Check this line for more info:
https://github.com/Tayx94/graphy/blob/5101eee48abbcadfbdee4c130b030ae554265fbf/Runtime/Util/G_Singleton.cs#L62
If you don't want that you can remove the Singleton inheritance in GraphyManager from : G_Singleton in here:
https://github.com/Tayx94/graphy/blob/5101eee48abbcadfbdee4c130b030ae554265fbf/Runtime/GraphyManager.cs#L32
But know that with this you will loose access to GraphyManager.Instance, so you will have to reference it directly wherever you use it.

**Comment by mgarbade** [comment]
Thanks for the quick reply. Is there another way of doing what I'd like to do?
I.e. using two buttons to enable / disable different modules individually?

example:
one button toggles "FPS"
the other button toggles "Advanced info"

**Comment by mgarbade** [comment]
I mean there are "Awake" functions in Both FPSManager and AdvancedManager but they seem to be overriden by the Settings chosen in the GraphyManager Component.

I tried multiple things:
- setting FPS manager to TEXT in GraphyManager Component -> but then deactivate the respective child game object (and attaching it to the above mentioned toggle). However this method leads to a heavy cascade of null exceptions

**Comment by Tayx94** [comment]
Yes, Graphy is not designed to be modified directly from the hierarchy for optimization purposes. 

What you could do is the following:
- Remove the Singleton inheritance in GraphyManager from : G_Singleton
- Duplicate the Graphy prefab for however many modules you want to toggle manually
- Setup different hotkeys to toggle Graphy in each of the prefabs.

With that you will have one Graphy prefab per module and you can toggle each individually

Also I don't know if you're aware that there is a hotkey to change modes directly, maybe that is good enough for what you want to do:
![image](https://github.com/Tayx94/graphy/assets/16625646/5e9d6abe-9be9-4ea2-b2e4-6a47bf5b6ec0)
