### ISSUE TITLE
UI.Text to TMPro.Text?

### ISSUE THREAD

**Issue by danoli3** [Tayx94/graphy#11]
Idea:

Support a A prefab version of Graphy using Text Mesh Pro (as to be performance enhanced so not getting bogged down by the UI System string bloat issues).

Since it's free now with unity might be a great idea to incorporate. I can have a go if you like.

**Comment by Tayx94** [comment]
That sounds interesting, although it requires the user to have TMPro. But if you think it's worth it go ahead! I would love to see how it performs :)
