### ISSUE TITLE
Why can't I just add this package via Packman > Add from git url?

### ISSUE THREAD

**Issue by ROBYER1** [Tayx94/graphy#111]
Same as the title, a simple way to install without adding extra stuff like openupm. 

Would be useful to document adding the scoped registry to packman to help people add the package through the Unity UI
![image](https://github.com/Tayx94/graphy/assets/10745594/c409f9b1-e7b9-4104-9a61-058620edbca7)

**Comment by Tayx94** [comment]
Hey man! First time I hear about Packman, can you elaborate a bit further?
I'm all for making Graphy easier to add to your project so please let me know how it works and the advantages it provides.

**Comment by Tayx94** [comment]
Ahh got it! That makes sense. Yeah when the readme was created I think Unity still didn't have that option, but now it makes total sense! Feel free to update the readme.md in a pull request and I'll review it 👍

**Comment by ROBYER1** [comment]
I'll sort this for you as soon as I'm back at my pc :) thanks!

**Comment by Tayx94** [comment]
Awesome and thank you as well! 😄

**Comment by ROBYER1** [comment]
Added a PR here for this https://github.com/ROBYER1/graphy/pull/1

**Comment by Tayx94** [comment]
Hey man! Looks great, but you need to open the MR into this repo, not your own fork. Else I cannot merge into master!
Thanks :)

**Comment by ROBYER1** [comment]
> Hey man! Looks great, but you need to open the MR into this repo, not your own fork. Else I cannot merge into master! Thanks :)

Sorry just sorted it with a PR to your repo, I've been so used to doing PRs and merges on Bitbucket that the Github web interface had me mixed up :)

**Comment by Tayx94** [comment]
Excellent! Thanks a lot, merged :)
