### ISSUE TITLE
Make the UI be responsive, compressing and expanding when modules are on/off

### ISSUE THREAD

**Issue by Tayx94** [Tayx94/graphy#15]
Remake the Graphy UI using Vertical and Horizontal Layout Groups.

**Comment by bcjordan** [comment]
May take a stab at this in the near future!

**Comment by Tayx94** [comment]
That'd be awesome! I tried it once, and it's a pretty big UI overhaul, but it can be done 😄

**Comment by br3aker** [comment]
Not sure if that's a good idea, at least for low-end platforms like smartphones or WebGL. As profiler should be as fast as possible, Layout Groups could be a [significant hit due to GetComponent calls](https://unity3d.com/how-to/unity-ui-optimization-tips).

**Comment by Tayx94** [comment]
Yes, I'm closing this.
