### ISSUE TITLE
[Suggestion] Rearange the repo so that we can use it as a submodule

### ISSUE THREAD

**Issue by Saarg** [Tayx94/graphy#18]
Hi,
first of all great asset, I bought it a few month before you made it free and it's served me right on all my project since.

I like to use [submodules](https://git-scm.com/book/en/v2/Git-Tools-Submodules) on my projects so that if I'm reusing an asset I can have 1 separate repository for the asset. I would love to do this with graphy without having to use the asset store but since this repository contains all the unity project and not just the `Graphy - Ultimate Stats Monitor` folder I can't do it.

I would suggest only having this folder in the repository.

**Comment by Tayx94** [comment]
Hey @Saarg !

That's a very good idea, I'll try to do it as soon as possible 😄

**Comment by Saarg** [comment]
Thanks, I'm honestly not sure how it could break compatibility with other users. The only way it could break something is if someone was cloning the repository and then moving the asset folder into their project but I guess they wouldn't mind the change?
Maybe a middle ground would be to keep the repository as the graphy-project and have another repository graphy-asset included in this project as a submodule? However I'm not sure how smooth the transition would be.

Anyway I understand and respect the fact that you are considering compatibility 👍

**Comment by Tayx94** [comment]
No worries, I'll take a look at it in the weekend and let you know ;)

**Comment by Tayx94** [comment]
master now supports upm.
