### ISSUE TITLE
Alt tabbing back into Unity reopens Graphy

### ISSUE THREAD

**Issue by QFSW** [Tayx94/graphy#21]
Steps:
1. Hide Graphy
2. Alt tab out of Unity
3. Alt tab back in to regain focus
4. Graphy will reopen on reload, yet it will still consider itself closed (so the hide key combo will need to be inputted twice to actually hide it again)

**Comment by Rockylars** [comment]
To add to this issue, Graphy will redo both it's size and hidden state, but will remember what it was in, the issue is visual.
