### ISSUE TITLE
Not working in AssetBundles

### ISSUE THREAD

**Issue by MeikelLP** [Tayx94/graphy#27]
**What**
AssetBundle with Scene A has an refrence to prefab `[Graphy]`.

When this prefab (and all its assets) is bundled into the same AssetBundle as Scene A it does work.
When this prefab (and all its assets) is bundled into its own AssetBundle it does not work.

**Cause**
This seems to be connected to a limitation of unity, which causes it to be unable to load shaders at runtime from AssetBundles.

**Solution**
The shader fields on the prefab must be replaced with materials in order to be loaded at runtime (as far as I know)

I can work around this with including graphy into the main application but I'd love to use graphy as an optional module.

**Comment by Tayx94** [comment]
Any updates on this? I haven't heard anyone else having problems with this, maybe Unity fixed it?

**Comment by MeikelLP** [comment]
Didn't touched it in years...
Sorry I dunno

**Comment by Tayx94** [comment]
No worries, thanks for answering, I'll close it for now then.
