### ISSUE TITLE
The shader sorting parameter is not being set. This causes the graphs to be rendered under other UI.

### ISSUE THREAD

**Issue by Tayx94** [Tayx94/graphy#38]

**Comment by Tayx94** [comment]
Cannot reproduce the bug in 5.4.0 or 2018.3.1, any help is welcome.

**Comment by Frost-Roach** [comment]
I'm the one who left the post in the asset store with the problem. Don't know if this helps but you never know.

I'm using unity version: 2018.2.11f1 (So slightly older)
The prefab is a child of the main camera which in turn is a child of a persistent gameobject.
The prefab Canvas uses Screen Space - Camera with sorting Layer always infront of anything else (Though I doubt that has any effect as it is the shader)

Anyways it doesn't seem like something that would effect a shader. I will update Unity and see if that fixes the problem.

**Comment by Frost-Roach** [comment]
Problem persists in 2018.3.2f1

**Comment by Tayx94** [comment]
Thanks for letting me know the setup to reproduce it. I think the issue may that the shader has some sorting issues in the Screen Space Camera mode. While I take a look at that I can suggest trying Overlay, as that mode should work ok.

**Comment by Tayx94** [comment]
Hello @Frost-Roach ! I managed to replicate the issue and committed a fix here:

https://github.com/Tayx94/graphy/commit/76405e93df91ff9b89983b70b322f604a5435b8f

Feel free to grab latest from master, and you should be good to go!

**Comment by Frost-Roach** [comment]
> Hello @Frost-Roach ! I managed to replicate the issue and committed a fix here:
> 
> [76405e9](https://github.com/Tayx94/graphy/commit/76405e93df91ff9b89983b70b322f604a5435b8f)
> 
> Feel free to grab latest from master, and you should be good to go!

Works like a charm, thanks for the fix :D

**Comment by Tayx94** [comment]
Thank you sir! I'm glad you're enjoying it ;)
