### ISSUE TITLE
Request: start hidden

### ISSUE THREAD

**Issue by hymerman** [Tayx94/graphy#4]
I can't see a way to start off hidden. I had a go at adding this, but the way the separate managers are set up and enabled, means that starting them off disabled loses some of the setup (e.g. positions).

I think to do this nicely, the toggling needs to exist on a game object one level up from the overall manager.

**Comment by DarkMio** [comment]
This commit enables that for you:

https://github.com/Tayx94/graphy/pull/5/commits/ea63cbf09b3cd3ca237fb0601546aac5bcace8b9

**Comment by Tayx94** [comment]
Reviewed and merged your commit DarkMio! Great job, I just had to make the commit from my project because you're using Unity 2017.1 and it broke compatibility with older versions.
