### ISSUE TITLE
Hide Graphy in Game view when it will be disabled

### ISSUE THREAD

**Issue by f0ff886f** [Tayx94/graphy#40]
If I add Graphy and set it to not be enabled on start, it still shows up in the Game Window in the Editor until I click Play.

Is it possible to hide it in the Game window until it is explicitly called by the script to be visible? It takes up a lot of screen estate and we still use that window when not in play mode to see camera shots, etc.

Thank you for the amazing plugin anyways!

**Comment by Tayx94** [comment]
This is a really good suggestion, that sadly isn't as straightforward as I thought 😄 
I'm discussing with people on the Discord on how the best way to do it would be. You can join the discussion there if you want: https://discord.gg/2KgNEHK

I will also update here with what we come up with.

**Comment by Tayx94** [comment]
Fixed!
