### ISSUE TITLE
Graphs don't work with OpenGLCore renderer

### ISSUE THREAD

**Issue by Tayx94** [Tayx94/graphy#47]
Not even with the LIGHT shader versions. The problem may be something related to the arrays used in the shader not being supported somehow.

**Comment by DrHeimdall** [comment]
Example screenshot (default asset store prefab as of 7/nov/19 in 2020.1.0a11 Linux OpenGL 4.5):
![alt-text](https://cdn.discordapp.com/attachments/406038157793165312/642028000325533706/unknown.png)

**Comment by alandavison** [comment]
I posted this on the Discord, but I'll also post it here for the sake of completeness.

Looks like you can at least work around the problem on line 103 of GraphStandard.shader.

```
// NOTE: The size of this array can break compatibility with some older GPUs
// If you see a pink box or that the graphs are not working, try lowering this value
// or using the GraphMobile.shader
				
uniform float GraphValues[512];
```

Reducing the size of that array to *anything* below 505 seems to make it work perfectly with OpenGLCore.

**Comment by Tayx94** [comment]
I'm going to assume this is fixed by using the LIGHT version of the shader, since that has `uniform float GraphValues[128];`
