### ISSUE TITLE
ScreenCapture.CaptureScreenshot compilation error on Unity2019.1.0f2 and Switch platform

### ISSUE THREAD

**Issue by ffyhlkain** [Tayx94/graphy#48]
I get a compilation error on Unity 2019.1.0f2 and Switch platform in the GraphyDebugger class at line 548.
It seems like the Switch platform wants rather to have the native screenshot code used (I can't give more info about that sadly due to Nintendos NDA. If you need more info about it, you need to register at the nintendos dev portal).

**Comment by Tayx94** [comment]
Thanks for bringing this up! But due to the closed nature of it we can't fix it. I'll mark it as wontfix, but if someone knows a workaround feel free to do it.
