### ISSUE TITLE
Unity 2019.3.x "Unity Reference Errors"

### ISSUE THREAD

**Issue by Mrgove10** [Tayx94/graphy#50]
In the latest unity alpha, importing the package results in missing references errors

**Comment by AskMeAgain** [comment]
When is the fix hitting the asset store?

**Comment by Mrgove10** [comment]
Will need to see whit @Tayx94

**Comment by Tayx94** [comment]
I'll try to push it this weekend 😄

**Comment by timothymarois** [comment]
Tried to import today, I believe it's hitting the same issues. Had to remove it from project.

**Comment by Mrgove10** [comment]
This fix works on unity 2019.x but seams to break on 2018.x and prior. The issue is that whit 2018.x missing references are not automatically ignored like in 2019.x

We will have to look if ```asmdef files``` can include conditions depending on the unity version to try ans fix this issue .

**Comment by Tayx94** [comment]
Good catch guys, I tested it on 5.4.0 and it works, but I think it's because it ignored asmdef files completely. Will revert versions in the meantime

**Comment by Tayx94** [comment]
Closed as Unity have apparently fixed their issues and backported the fix to all versions.
