### ISSUE TITLE
Shader issue with LWRP/Universal SRP (Didn't check HDRP, but chances are good it will be a similar result)

### ISSUE THREAD

**Issue by MostHated** [Tayx94/graphy#63]
I was trying out the Universal SRP in 2019.3b and the LWRP in 2019.2 (same thing, new name) and noticed Graphy having a stroke. Looks like the FPS shader isn't too happy. 

Here it is in normal mode: https://i.imgur.com/Uuuj3te.gifv
and here in light mode: https://i.imgur.com/PyuMnyh.gifv

I mentioned in Discord but will mention again in case it is lost in chat, with 19.3's release, LWRP/Universal RP will be default going forward and I don't believe there will be a non-SRP renderer.

**Comment by Tayx94** [comment]
I'll label this as wontfix for now, if it still happens we can reopen.
