### ISSUE TITLE
Issue with Average Frame Rate

### ISSUE THREAD

**Issue by Reddevildragg** [Tayx94/graphy#64]
Latest version on the asset store looks to have an issue with the average frame rate. When the samples are full just refreshes the last sample while even when slowing the app down the average stays the same.

            if (m_avgFpsSamplesCount < m_avgFpsSamplesCapacity)
            {
                m_avgFpsSamplesCount++;
            }
            else
            {
                m_avgFpsSamplesCount = 0;
            }

appeared to fix in the the g_fpsmonitor.cs line 88 but not sure if this is how it was intended to work

**Comment by SuperPenguin** [comment]
it's already fixed on master branch
https://github.com/Tayx94/graphy/pull/59

**Comment by Tayx94** [comment]
It is, thanks for bringing it up @Reddevildragg 😄
