### ISSUE TITLE
NullReferenceException in Editor after a Hot-Swap when Graphy is disabled

### ISSUE THREAD

**Issue by scscgit** [Tayx94/graphy#68]
While in Editor, if Graphy is disabled (e.g. by default via Ctrl+H) and a Hot-Swap occurs (alt+tabbing into Unity after any script was modified), the OnApplicationFocus() calls UpdateParameters() on both FpsGraph and AudioGraph while their m_shaderGraph == null, throwing a NullReferenceException.

My solution is to simply return those functions if m_shaderGraph == null, so there should be some code review in order to make sure this doesn't cause any new issues. I noticed that in RamGraph, the UpdateParameters() calls Init() if any variable with a m_shaderGraph* prefix is null, so this may be possibly a better solution. Why are those classes even implemented differently, was it just an oversight?

My question is though, why are the Update* methods even getting called? If the Graphy is completely disabled, why does it even do anything, and why does it require any initialization? I've checked some of your README materials, and I don't see any "zero performance cost if disabled" stated anywhere. Does that mean this extension is unstable and shouldn't be used in production? Please make sure this isn't the case :)

Tested in Unity 2019.2.8f1

**Comment by scscgit** [comment]
Fixed in PR https://github.com/Tayx94/graphy/pull/69

**Comment by SuperPenguin** [comment]
Related to this https://github.com/Tayx94/graphy/issues/67, probably won't fix.
When you toggle active to disable, it's the modules scripts that is disabled, the GraphyManager still enabled, so it's not zero performance when disabled either, Graphy still need GraphyManager to listen to any hotkey and re-enable the modules.

**Comment by scscgit** [comment]
Oh I didn't notice that #67 actually had the same issue, they didn't mention the critical detail that it only happens **when Graphy is disabled**, which is the case based on my observation. I noticed the response that it's "not worth fixing as recompiling while Unity is running is not supported and will create strange behaviours.". What the hell? Hot-swapping is a completely normal part of development, and the fix only takes a couple of seconds. If you don't understand how the lifecycle of functions like OnEnable work, then just let the contributors do it. I don't see any "strange behaviours" with hot-swaps, and it's not like there is any excuse to throw exceptions when the extension is completely disabled. Sure, if you want to take care of optional features like "Keep Alive", maybe there are some static fields you would have to check, It's not like we can't disable a feature or two if they are truly hard to support with Hot-Swap.

More importantly, I understand that it can't literally be "zero-performance cost", but the hotkey support is definitely acceptable compared to initialization and update costs :) It's literally only a matter of a single condition.

**Comment by scscgit** [comment]
Actually now that I think more about the OnApplicationFocus() part of the lifecycle - this occurs every time a user clicks to the Game view (e.g. after interacting with a Scene or an Inspector), or when he clicks in any external window and returns back, and it completely wipes out all the histographs. Isn't that also a huge issue, as the wipe unnecessarily occurs even if everything is already initialized? I believe developers would prefer to work in editor without having the history reset every few seconds (as the main use-case is to aid in debugging).
