### ISSUE TITLE
NullRef for EditorStyles.boldlabel

### ISSUE THREAD

**Issue by Flavelius** [Tayx94/graphy#7]
in LoadGuiStyles() (GraphyDebugEditor & GraphyManagerEditor). 
Can be fixed by calling it once in OnGUI (as the editor styles are not initialized before the first OnGUI event)

**Comment by Tayx94** [comment]
Good catch, will try to fix it today or tomorrow :)

**Comment by Tayx94** [comment]
@Flavelius which Unity version are you using? I can't seem to be able to reproduce the error.

**Comment by Flavelius** [comment]
2017.4.6f1. I downloaded the repo and removed the sample scene (+ scripts).

**Comment by Tayx94** [comment]
Applied your fix, I hope this resolves the issue for everyone in the future, although I don't like doing it this way, because it shouldn't need to be updated every OnGUI() update.

**Comment by Flavelius** [comment]
stylesloaded = false;

if (!stylesLoaded) {LoadStyles(); stylesLoaded = true;}

that's how i did it and it worked fine

**Comment by Tayx94** [comment]
Cool! I may do it that way in the future
