### ISSUE TITLE
Editor throws "Index of ouf range" exception when plugin is imported via UPM

### ISSUE THREAD

**Issue by ffyhlkain** [Tayx94/graphy#77]
When distributing the plugin via UPM, the editor inspector will run into index out of range exceptions in the GraphyEditorStyle.cs file. Basically the code assumes that the plugin will be located in the assets folder, which is true as long as it is not imported via the UPM (in that case it is under Packages or Library/PackageCache folder).

GraphyEditorStyle.cs.cs
```
            path = GetPath();
            path = path.Split(new string[] { "Assets" },StringSplitOptions.None)[1]
                       .Split(new string[] { "Graphy" },StringSplitOptions.None)[0];
```

**Comment by Tayx94** [comment]
Fixed in dev, will merge into master soon.
