### ISSUE TITLE
Version control

### ISSUE THREAD

**Issue by favoyang** [Tayx94/graphy#78]
Hi @Tayx94,

Thanks for making this awesome UPM package. I'm the creator of the OpenUPM platform, an open-source UPM registry, and continuous build service based on Git tags. It's hosting more than 200+ open-source UPM packages at the time of writing.

A folk submitted your packages to the platform which brings me here. https://openupm.com/packages/com.tayx.graphy/

It looks good, but OpenUPM still needs a valid Git Tag to work with. You already have GitHub releases (which created Git tags) based on the master branch. However, the upm branch is ahead of the master branch. So our build pipelines failed to locate the package.json from existing Git tags.

If this makes sense for you, please consider two solutions
1. You can create an extra tag `upm/x.y.z` tag (based on the upm branch) along with the `x.y.z` tag (based on the master branch). Then I can set our pipelines to track tag with `upm` prefix only. This will be the easiest way to go. But you probably need a tool to automate the tagging.
1. You can also merge the changes from the upm branch back to the master branch. Our pipelines can locate the position of the package.json. Then you just do regular GitHub release. You can keep the upm branch synced with [Github Actions](https://medium.com/openupm/how-to-maintain-upm-package-part-1-7b4daf88d4c4). This is a better way to go, you get auto-synced upm branch and you don't need to do extra tagging.

**Comment by Tayx94** [comment]
The master branch now supports UPM. Only issue is that OpenUPM reports the built version is 1.6.0, when it should be 2.0.0. 

Is there something I'm doing wrong?

**Comment by favoyang** [comment]
Thanks for the response. The issue is caused by the mismatched version: the Git tag is 2.0.0-Unity2019.3, while the package.json version is 1.6.0. You could bump the version then create a new tag to fix it.

BTW, the -Unity2019.3 suffix is not necessary. You have set the value in the package.json. So the Git tag can be just 2.0.0.

**Comment by Tayx94** [comment]
Ok perfect thanks! I'll update it and make a new tag. I wanted to add the -Unity2019.3 suffix to the first release that is going to support it so people understand that now that's the minimum version supported.

**Comment by favoyang** [comment]
Looks great. Version 2.0.1 is available now.
