### ISSUE TITLE
Graphs only show up in one eye in VR

### ISSUE THREAD

**Issue by CConchelos** [Tayx94/graphy#79]
URP 2019.3.15f1 Single Pass Instanced
The graphs for FPS and RAM are only showing up in the right eye. 

In GraphStandard.shader, there are 3 code blocks to assist with this issue.
Each is wrapped with 

#if UNITY_2017_1_OR_NEWER
    --code here
#endif

removing these preprocessor blocks I was able to see the graphs in both eyes.

I can see that I have the keyword UNITY_2017_1_OR_NEWER in other assets in my project.
Maybe these preprocessor blocks work in scripts but not in shaders?

**Comment by Tayx94** [comment]
Removed those defines in dev branch, will merge into master soon.
