### ISSUE TITLE
Toggle mode doesn't take "module state" into consideration

### ISSUE THREAD

**Issue by ghost** [Tayx94/graphy#8]
Pretty easy to replicate. Turn off audio and advanced modules press the togle mode hotkey a few times and you will have disabled modules displayed

**Comment by Tayx94** [comment]
This was the expected behaviour, that way you can activate other modules from runtime if you want. But that functionality could be implemented with some modifications. I'll leave this open so other people can contribute ideas on how to implement hotkeys for Graphy and how should these behave.

**Comment by Tayx94** [comment]
Closing this as no one else has had this issue.
