### ISSUE TITLE
Tag upm branch with 1.5.2-upm for compatiablity with openUPM

### ISSUE THREAD

**Issue by Reddevildragg** [Tayx94/graphy#81]
https://openupm.com/packages/com.tayx.graphy/

openupm currently using none upm branch in its build, tagging a upm package with 1.5.2-upm should override this and allow openupm to process package correctly

unfortunally can not add tags as a pull request so can not resolve myself.

**Comment by Tayx94** [comment]
master now supports upm, closed!
