### ISSUE TITLE
build error unity 2019.4.8f1

### ISSUE THREAD

**Issue by extrawurst** [Tayx94/graphy#83]
installed unitypackage from GitHub release: https://github.com/Tayx94/graphy/releases/tag/v2.0.0-Unity2019.3

```
Assets/Tayx/Graphy - Ultimate Stats Monitor/Scripts/GraphyDebugger.cs(548,21): error CS0103: The name 'ScreenCapture' does not exist in the current context
```

**Comment by Tayx94** [comment]
@extrawurst can you check if you have this built in package disabled?

![image](https://user-images.githubusercontent.com/16625646/97288040-96fe7280-1845-11eb-881d-1038dcbd2ddf.png)

**Comment by Tayx94** [comment]
Closing this until someone else reports it.
