### ISSUE TITLE
[InputSystem] The function CheckForKeyPress requires a null check for "Keyboard.current"

### ISSUE THREAD

**Issue by Piorimu** [Tayx94/graphy#86]
Keyboard.current will be null when transitioning from a scene that uses OnScreenButton to a scene that does not use it.
Therefore, NullReferenceException occurs at the time of scene transition in the functions CheckFor1KeyPress, CheckFor2KeyPress, and CheckFor3KeyPress.

**Comment by mattiaswargren** [comment]
+1 

Would be nice to have more control on (console) platforms that does not support Keyboard (yet)

**Comment by Tayx94** [comment]
Added a quick null check here:

https://github.com/Tayx94/graphy/releases/tag/v2.1.3

If this is still an issue I'll reopen it.
