### ISSUE TITLE
Unity asset store version out of date

### ISSUE THREAD

**Issue by SeanBannister** [Tayx94/graphy#88]
Hi, thanks so much for this plugin. I just noticed the unity asset store version is out of date compared to this repo. Be handy if it stayed up to date for those of us that like to get alerted to version updates through the package manager.

**Comment by Tayx94** [comment]
Fixed!

**Comment by ManuelRauber** [comment]
@Tayx94 Is this the case again? 

Latest version on the Asset Store is 2.1.3. Here on GitHub there is already v3. :)

![image](https://user-images.githubusercontent.com/740791/219308630-da9c1b61-0965-4ac8-a37b-fedd70127ba3.png)

**Comment by Tayx94** [comment]
You are correct! I'll try to do some tidying up on the weekend and update the store version, thanks!

**Comment by Tayx94** [comment]
Updated the asset store version, it will be the same as GitHub in a couple of days, just waiting for Unity to approve
