### ISSUE TITLE
FindAudioListener issue 

### ISSUE THREAD

**Issue by decimate** [Tayx94/graphy#89]
I'm running 2020.3.4f1

Graphy v1.5.2 was working okay for me.

But after upgrading to v2.1.1 I'm getting the following errors which relate to the "AUDIO - Module".

My Boot scene only contains a GameManager and a Preloader. 
The GameManager handles scene loading, plus various persistent prefabs, including a AudioManager singleton.

It was work okay v1.5.2, but something has changed. 

-------

NullReferenceException: Object reference not set to an instance of an object
Tayx.Graphy.Audio.G_AudioMonitor.FindAudioListener () (at Assets/Graphy - Ultimate Stats Monitor/Runtime/Audio/G_AudioMonitor.cs:181)
Tayx.Graphy.Audio.G_AudioMonitor.UpdateParameters () (at Assets/Graphy - Ultimate Stats Monitor/Runtime/Audio/G_AudioMonitor.cs:145)
Tayx.Graphy.Audio.G_AudioMonitor.Init () (at Assets/Graphy - Ultimate Stats Monitor/Runtime/Audio/G_AudioMonitor.cs:201)
Tayx.Graphy.Audio.G_AudioMonitor.Awake () (at Assets/Graphy - Ultimate Stats Monitor/Runtime/Audio/G_AudioMonitor.cs:70)

NullReferenceException: Object reference not set to an instance of an object
Tayx.Graphy.Audio.G_AudioMonitor.FindAudioListener () (at Assets/Graphy - Ultimate Stats Monitor/Runtime/Audio/G_AudioMonitor.cs:181)
Tayx.Graphy.Audio.G_AudioMonitor.UpdateParameters () (at Assets/Graphy - Ultimate Stats Monitor/Runtime/Audio/G_AudioMonitor.cs:145)
Tayx.Graphy.Audio.G_AudioManager.UpdateParameters () (at Assets/Graphy - Ultimate Stats Monitor/Runtime/Audio/G_AudioManager.cs:184)
Tayx.Graphy.Audio.G_AudioManager.Start () (at Assets/Graphy - Ultimate Stats Monitor/Runtime/Audio/G_AudioManager.cs:59)

<img width="471" alt="Screen Shot 2021-04-17 at 2 18 34 pm" src="https://user-images.githubusercontent.com/49468438/115103671-aeb1ea80-9f8e-11eb-9a00-aa8ad44c9aec.png">

**Comment by Tayx94** [comment]
Good find! Fixed here:

https://github.com/Tayx94/graphy/releases/tag/v2.1.2

**Comment by decimate** [comment]
Thank you!

That's working perfectly  now.
