### ISSUE TITLE
FPS Graph rendering fails when editor is defocused and refocused

### ISSUE THREAD

**Issue by ChrisDirkis** [Tayx94/graphy#9]
Before:
![image](https://user-images.githubusercontent.com/7120990/43371550-a09fd080-93d7-11e8-9ff2-d45d053bd787.png)

After:
![image](https://user-images.githubusercontent.com/7120990/43371552-a71b1bd6-93d7-11e8-9c57-75c57a83d953.png)

Only happens in editor, not in build. Unity 2018.1.6f1, Windows, .NET4.6 scripting runtime.

Might be a shader initialization issue?

**Comment by Tayx94** [comment]
Hey @ChrisDirkis ! I implemented a fix that I hope removes this issue, please let me know if it happens again 😄

**Comment by ChrisDirkis** [comment]
After a test: clicking out of the editor and back in resets the graph, but it runs perfectly even when that happens. Consider that a **solved** for me.
