### ISSUE TITLE
[Feature request] Supports safe area.

### ISSUE THREAD

**Issue by Haruma-K** [Tayx94/graphy#99]
Thanks for your great library.

On mobile platforms, the GUI appears outside the safe area.
I think it would be better if there is an option to limit it to within the safe area.

![image](https://user-images.githubusercontent.com/47441314/184169174-5f275c70-083b-4700-bb21-4c503b6c1873.png)

**Comment by Artein** [comment]
That is super annoying. Please, fix this!

**Comment by Tayx94** [comment]
> That is super annoying. Please, fix this!

I'm quite busy at the moment, but remember this a completely open source tool! If it's so annoying feel free to open up a pull request with a fix so you can help other people too.

**Comment by Haruma-K** [comment]
@Tayx94 
You are right, this is open source! I have created a PR and you can use it if you like.
https://github.com/Tayx94/graphy/pull/101
